# Setting is based on measurements taken at the experiment on the 27th of October
# 2023. Several tablets were positioned in a square around a central table. 
# Additionally, some benches were placed besides the walkable area.
#
# IDs of the objects end in a dot to make it easier to recognize the relationship
# between goal and object
setting <- background(shape = rectangle(center = c(10, 5), 
                                        size = c(20, 10)),
                      objects = list(rectangle(id = "table.",
                                               center = c(10.083, 5.179),
                                               size = c(1.8, 0.4),
                                               interactable = TRUE),
                                               
                                     rectangle(id = "tablet 1.",
                                               center = c(15.000, 3.596),
                                               size = c(0.2, 0.2),
                                               interactable = TRUE),
                                     rectangle(id = "tablet 2.",
                                               center = c(15.058, 1.162),
                                               size = c(0.2, 0.2),
                                               interactable = TRUE),
                                     rectangle(id = "tablet 3.",
                                               center = c(11.716, 1.354),
                                               size = c(0.2, 0.2),
                                               interactable = TRUE),
                                     rectangle(id = "tablet 4.",
                                               center = c(8.231, 1.306),
                                               size = c(0.2, 0.2),
                                               interactable = TRUE),

                                     rectangle(id = "tablet 5.",
                                               center = c(5.060, 1.262),
                                               size = c(0.2, 0.2),
                                               interactable = TRUE),
                                     rectangle(id = "tablet 6.",
                                               center = c(5.084, 3.576),
                                               size = c(0.2, 0.2),
                                               interactable = TRUE),
                                     rectangle(id = "tablet 7.",
                                               center = c(4.966, 6.494),
                                               size = c(0.2, 0.2),
                                               interactable = TRUE),
                                     rectangle(id = "tablet 8.",
                                               center = c(4.833, 9.122),
                                               size = c(0.2, 0.2),
                                               interactable = TRUE),
                                               
                                     rectangle(id = "tablet 9.",
                                               center = c(8.351, 9.141),
                                               size = c(0.2, 0.2),
                                               interactable = TRUE),
                                     rectangle(id = "tablet 10.",
                                               center = c(11.630, 9.000),
                                               size = c(0.2, 0.2),
                                               interactable = TRUE),
                                     rectangle(id = "tablet 11.",
                                               center = c(14.889, 9.064),
                                               size = c(0.2, 0.2),
                                               interactable = TRUE),
                                     rectangle(id = "tablet 12.",
                                               center = c(14.948, 6.517),
                                               size = c(0.2, 0.2),
                                               interactable = TRUE),
                                               
                                     rectangle(id = "bench 1.",
                                               center = c(0.50, 7.50), 
                                               size = c(0.2, 2.0),
                                               interactable = TRUE),
                                     rectangle(id = "bench 2.",
                                               center = c(1.50, 7.50), 
                                               size = c(0.2, 2.0),
                                               interactable = TRUE),
                                     rectangle(id = "bench 3.",
                                               center = c(2.50, 7.50), 
                                               size = c(0.2, 2.0),
                                               interactable = TRUE),
                                     rectangle(id = "bench 4.",
                                               center = c(0.50, 4.50), 
                                               size = c(0.2, 2.0),
                                               interactable = TRUE),
                                     rectangle(id = "bench 5.",
                                               center = c(1.50, 4.50), 
                                               size = c(0.2, 2.0),
                                               interactable = TRUE),
                                     rectangle(id = "bench 6.",
                                               center = c(2.50, 4.50), 
                                               size = c(0.2, 2.0),
                                               interactable = TRUE)),
                      entrance = c(0, 1.2))
